server:
  port: 8236

spring:
  datasource:
    url: jdbc:mysql://39.107.230.204:3306/museum?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis设置
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  # type-aliases-package: edu.nwu.Museum.backstage.domain
